/* tslint:disable */
/* eslint-disable */
/**
 * CasaOS App Management API
 * CasaOS App Management manages app lifecycle, including installing, uninstalling, starting, stopping, setting, etc.  For issues, please visit the [GitHub repository](https://github.com/ReCasaOS/CasaOS-AppManagement). 
 *
 * The version of the OpenAPI document: v2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

